# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  subscriptionName: 'AZR-RAC-POC1'  
  tenantId: '770a2450-0227-4c62-90c7-4e38537f1102'
  containerRegistryFullName: 'Race2ACR'
  appName: 'race2securityprovider'
  dockerFilename: 'Dockerfile_SecurityProvider'
  adoSpClientId: '39ef2527-ca88-4bbc-b474-2d9aecf67f46'
  dockerFilePath: './Dockerfile_SecurityProvider'
  azureServiceConnection: 'AZR-RAC-POC1'

stages:
- stage : Buildandpush
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2 
      displayName: 'Build and publish helm chart and container image to Azure Container Registry' 
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        useGlobalConfig: false    
        inlineScript: |
          az --version
          az login --service-principal -u $(adoSpClientId) -p $(adoSpClientSecret) --tenant $(tenantId) 
          az acr build -r $(containerRegistryFullName) -t $(containerRegistryFullName).azurecr.io/$(appName):v5 -f $(Build.SourcesDirectory)/RACE2/$(dockerFilename) $(Build.SourcesDirectory)/RACE2
        