# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  repository_securityprovider: 'race2securityprovider'
  dockerfile_securityprovider: '$(Build.SourcesDirectory)/RACE2/Dockerfile_SecurityProvider'
  repository_webapi: 'race2webapi'
  dockerfile_webapi: '$(Build.SourcesDirectory)/RACE2/Dockerfile_WebApi'
  repository_frontendwebserver: 'race2frontendwebserver'
  dockerfile_frontendwebserver: '$(Build.SourcesDirectory)/RACE2/Dockerfile_FrontEndWebServer'
  containerRegistry: 'AZR-RAC-DEV1-DockerRegistry'
  tag: 'latest'
  azureServiceConnection: 'AZR-RAC-DEV1'
  resourceGroupName: 'DEVRACINFRG1401'
  templateFile: '$(Build.SourcesDirectory)/RACE2/bicepfiles/createAllContainerApps.bicep'
  parameterfile: '$(Build.SourcesDirectory)/RACE2/DeploymentYamlFiles/deployAllContainerAppsParametersDEV.json'

stages:
- stage : DeployContainerApps
  displayName: Deploy Container Apps to Azure Portal
  jobs:  
  - job: Deploy
    displayName: Deploy Container Apps to Azure Portal
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2 
      displayName: 'Deploy Container Apps to Azure Portal' 
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        useGlobalConfig: false    
        inlineScript: |
          az --version
          az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) -p @$(parameterfile)
