# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  subscriptionName: 'AZR-RAC-POC1'
  adoSpClientId:'39ef2527-ca88-4bbc-b474-2d9aecf67f46'
  adoSpClientSecret:'P8J8Q~bvpvv9brjyqqCxriIlloll_WvyAiQQfc.-'
  tenantId: '770a2450-0227-4c62-90c7-4e38537f1102'
  containerRegistryFullName: 'Race2ACR'
  appName: 'Race2ImagePOC'
stages:
- stag:
me: Build and push stagecontainerRegistryFullName
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImageName)
    steps:subscriptionName
    - task: AzurePowerShell@5 
      displayName: 'Build and publish helm chart and container image to Azure Container Registry' 
      inputs: azureSubscription: $(subscriptionName) 
      ScriptType: 'InlineScript' Inline: | 
        az login --service-principal -u $(adoSpClientId) -p $(adoSpClientSecret) --tenant $(tenantId) 
        if ($LastExitCode -ne 0) { Write-Host “##vso[task.complete result=Failed;]DONE” exit 1 } 
        cd $(Build.SourcesDirectory) 
        az acr build --image $(containerRegistryFullName)/$(appName):$(tag) --registry $(containerRegistryFullName) --platform 'linux/amd64'  --build-arg INTERNAL_FEED_ACCESSTOKEN=$(System.AccessToken) --file $(dockerFilePath) . 
        if ($LastExitCode -ne 0) { Write-Host “##vso[task.complete result=Failed;]DONE” exit 1 }
