# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  - name: repository
    value: 'Race2ACR'
  - name: dockerfile
    value: '$(Build.SourcesDirectory)/RACE2/Dockerfile_SecurityProvider'
  - name: containerRegistry
    value: 'AZR-RAC-POC1-DockerRegistry'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image
      inputs:
        command: buildAndPush
        repository: ${{ variables.repository }}
        dockerfile: ${{ variables.dockerfile }}
        containerRegistry: ${{ variables.containerRegistry }}
        tags: $(Build.BuildId)
