trigger:
- none
pr:
- none

name: Deploy FunctionApp

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'AZD-RAC-POC1'
  resourceGroupName: 'POCRACINFRG1402' 
  templateFile: './RACE2/bicepfiles/createfunctionapp.bicep'
  parameterFile: './RACE2/bicepfiles/createfunctionapp_poc.bicepparam'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2  
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false    
    inlineScript: |
      az --version
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters $(parameterFile)