trigger:
- main

name: Deploy LogAnalytics Workspace

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'AZR-RAC-POC1'
  resourceGroupName: 'RACE2ProjectRG1' 
  templateFile: './RACE2/bicepfiles/createappworkspace.bicep'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2  
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false    
    inlineScript: |
      az --version
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters logAnalyticsWorkspaceName="race2appworkspace"
