trigger:
- none
pr:
- none

name: Deploy Sql Server

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'AZR-RAC-POC1'
  resourceGroupName: 'POCRACINFRG1401' 
  templateFile: './RACE2/bicepfiles/createsqlserver.bicep'
  parameterfile: './RACE2/bicepfiles/createsqlserver.bicepparam'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2  
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false    
    inlineScript: |
      az --version
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) -p $(parameterfile)
