trigger:
- none
pr:
- none

name: Deploy All Resources

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'AZD-RAC-POC1'
  resourceGroupName: 'POCRACINFRG1402'
  location: 'uksouth' 
  templateFileAllResources: './RACE2/bicepfiles/createallresources.bicep'
  parameterfileAllResources: './RACE2/bicepfiles/createallresourcesPOC.bicepparam'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2  
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false    
    inlineScript: |
      az --version
      az group create -n $(resourceGroupName) -l $(location)     
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFileAllResources) --parameters $(parameterfileAllResources)
