trigger:
- main

name: Deploy Container App Env

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'AZR-RAC-POC1'
  resourceGroupName: 'RGPRACE2ALLRESOURCES201' 
  templateFile: './RACE2/bicepfiles/createwebapicontainerapp.bicep'
  parametersFile: './RACE2/DeploymentYamlFiles/deployContainerAppParameters.json'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2  
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false    
    inlineScript: |
      az --version
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) -p @$(parametersFile)
