trigger:
- main

name: Deploy ResourceGroup

variables:
  vmImageName: 'ubuntu-latest'
  templateFile: './RACE2/bicepfiles/createresourcegroup.bicep'
  parameterFile: './RACE2/DeploymentYamlFiles/race2Parameters.json'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: azureServiceConnection
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      az group create --template-file $(templateFile) --parameters @$(parameterFile)
