trigger:
- main

name: Deploy Container Registry

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: 'AZR-RAC-POC1'
  resourceGroupName: 'RACE2ProjectRG1' 
  templateFile: './RACE2/bicepfiles/main.bicep'
  parameterfile: './RACE2/DeploymentYamlFiles/deployAlResources.json'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2  
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false    
    inlineScript: |
      az --version
      az deployment sub create  --template-file $(templateFile) -p @$(parameterfile)
