trigger:
- main

name: Deploy ResourceGroup

variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'AZR-RAC-TST1'
  resourceGroupName: 'TSTRACINFRG1401'
  templateFile: './RACE2/bicepfiles/createSecretsKeysBlobs.bicep'
  parametersFile: './RACE2/bicepfiles/createSecretsKeysBlobsDEV.bicepparam'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) -p $(parametersFile)