trigger:
- main

name: Deploy ResourceGroup

variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'AZR-RAC-POC1'
  location : 'westeurope'
  resourceGroupName: 'RACE2ProjectRG1'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)