trigger:
- none
pr:
- none

name: Deploy ResourceGroup

variables:
  vmImageName: 'ubuntu-latest'
  azureServiceConnection: 'AZD-RAC-POC1'
  resourceGroupName: 'POCRACINFRG1402'
  templateFile: './RACE2/bicepfiles/createSecretsKeysBlobs.bicep'
  parametersFile: './RACE2/bicepfiles/createSecretsKeysBlobsPOC.bicepparam'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) -p $(parametersFile)