trigger:
- main

name: Deploy ResourceGroup

variables:
  vmImageName: 'ubuntu-latest'
  templateFile: './RACE2/bicepfiles/createresourcegroup.bicep'
  parameterFile: './RACE2/DeploymentYamlFiles/deployResourceGroupParameters.json'
  azureServiceConnection: 'AZR-RAC-POC1'
pool:
  vmImage: $(vmImageName)

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az group create --template-file $(templateFile) --parameters @$(parameterFile)
