FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["RACE2.FrontEndWebServer/RACE2.FrontEndWebServer.csproj", "RACE2.FrontEndWebServer/"]
COPY ["RACE2.DataAccess/RACE2.DataAccess.csproj", "RACE2.DataAccess/"]
COPY ["RACE2.DataModel/RACE2.DataModel.csproj", "RACE2.DataModel/"]
COPY ["RACE2.Dto/RACE2.Dto.csproj", "RACE2.Dto/"]
RUN dotnet restore "RACE2.FrontEndWebServer/RACE2.FrontEndWebServer.csproj"
COPY . .
WORKDIR "/src/RACE2.FrontEndWebServer"
RUN dotnet build "RACE2.FrontEndWebServer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RACE2.FrontEndWebServer.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RACE2.FrontEndWebServer.dll"]