FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["RACE2.SecurityProvider/RACE2.SecurityProvider.csproj", "RACE2.SecurityProvider/"]
COPY ["RACE2.Services/RACE2.Services.csproj", "RACE2.Services/"]
COPY ["RACE2.DataAccess/RACE2.DataAccess.csproj", "RACE2.DataAccess/"]
COPY ["RACE2.DataModel/RACE2.DataModel.csproj", "RACE2.DataModel/"]
RUN dotnet restore "RACE2.SecurityProvider/RACE2.SecurityProvider.csproj"
COPY . .
RUN dotnet build "RACE2.SecurityProvider/RACE2.SecurityProvider.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RACE2.SecurityProvider/RACE2.SecurityProvider.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RACE2.SecurityProvider.dll"]
