FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["RACE2.WebApi/RACE2.WebApi.csproj", "RACE2.WebApi/"]
COPY ["RACE2.Common/RACE2.Common.csproj", "RACE2.Common/"]
COPY ["RACE2.Infrastructure/RACE2.Infrastructure.csproj", "RACE2.Infrastructure/"]
COPY ["RACE2.DatabaseProvider/RACE2.DatabaseProvider.csproj", "RACE2.DatabaseProvider/"]
COPY ["RACE2.Services/RACE2.Services.csproj", "RACE2.Services/"]
COPY ["RACE2.DataAccess/RACE2.DataAccess.csproj", "RACE2.DataAccess/"]
COPY ["RACE2.Dto/RACE2.Dto.csproj", "RACE2.Dto/"]
COPY ["RACE2.DataModel/RACE2.DataModel.csproj", "RACE2.DataModel/"]
COPY ["RACE2.Logging/RACE2.Logging.csproj", "RACE2.Logging/"]
COPY ["RACE2.Notification/RACE2.Notification.csproj", "RACE2.Notification/"]
RUN dotnet restore "RACE2.WebApi/RACE2.WebApi.csproj"
COPY . .
WORKDIR "/src/RACE2.WebApi"
RUN dotnet build "RACE2.WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RACE2.WebApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RACE2.WebApi.dll"]