version: '3.4'

services:
  race2.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  race2.securityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  race2.frontendweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  race2.frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

