apiVersion: apps/v1
kind: Deployment
metadata:
  name: race2securityprovider-deployment
  namespace: securityprovider
spec:
  selector:
    matchLabels:
      app: race2securityprovider-pod
  template:
    metadata:
      labels:
        app: race2securityprovider-pod
    spec:
      containers:
      - name: race2securityprovider-container
        image: race2acr.azurecr.io/securityprovider:v1
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: Production
        - name: "SqlConnection"
          value: "Server=tcp:race2sqlserver.database.windows.net,1433;Initial Catalog=RACE2Database;Persist Security Info=False;User ID=race2admin;Password=Race2Password123!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        - name: "RACE2FrontEndURL"
          value: "http://localhost:5001"
        - name: "RACE2WebApiURL"
          value: "http://localhost:5003/graphql/"
        - name: "RACE2WebAppURL"
          value: "http://localhost:5010"
          
