name: docker-build-push-workflow

on:
  push:
    branches: [none] # [ main ]
  pull_request:
    branches: [none] # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build-container:

     runs-on: ubuntu-latest
     defaults:
      run:
        shell: bash
        working-directory: RACE2

     steps:
     - name: 'Login via Azure CLI'
       uses: azure/login@v1
       with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
     - name: 'Checkout'
       uses: actions/checkout@v3
     - name: 'Azure CLI Login'
       uses: azure/docker-login@v1
       with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
     - name: 'Docker build and push'    
       run: |
          docker build . -f Dockerfile_SecurityProvider -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/race2securityprovider:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/race2securityprovider:${{ github.sha }}
