on: 
  workflow_dispatch:
name: Docker Image Build and Push
env:
  IMAGE_NAME: departments-api
permissions:
  id-token: write
  contents: read
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: Checkout repository
          uses: actions/checkout@v3     
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - name: Build the frontend image and push it to ACR          
          uses: docker/build-push-action@v2
          with:
            working-directory: RACE2
            push: true
            tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/aspcoresample:v1
            file: ./RACE2/Dockerfile_SecurityProvider
            
