on: [workflow_dispatch]
name: Docker Image Build and Push
permissions:
  id-token: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy
      uses: azure/CLI@v1.0.7
      with:
        azcliversion: agentazcliversion
        inlineScript: |
          az deployment group create --name BicepDeployment --resource-group ${{ secrets.RG_NAME }} --template-file "./RACE2/githubAction Deployment files/main.bicep"
          echo "BLOB_URL=$(az deployment group show -g ${{ secrets.RG_NAME }} -n BicepDeployment --query properties.outputs.blobURL.value -o tsv)" >> $GITHUB_ENV

    - name: print env variable
      run: echo "${{ env.BLOB_URL }}"
