name: docker-build-workflow

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build-container:

     runs-on: ubuntu-latest
     defaults:
      run:
        shell: bash
        working-directory: RACE2

     steps:
      - uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -f Dockerfile_SecurityProvider -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/race2securityprovider:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/race2securityprovider:${{ github.sha }}
